version: '3'

services: 
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../:/var/www/html/
    expose:
      - 9000
    depends_on: 
      - db
  nginx:
    image: nginx
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 9400:9600
    depends_on:
      - php-fpm
  db:
    image: mariadb
    volumes: 
      - dataBulk:/var/etc/mysql
    ports: 
      - 3307:3306
    environment:
      MYSQL_DATABASE: eCommerce
      MYSQL_ROOT_PASSWORD: 123456


volumes: 
  dataBulk: